### ISSUE TITLE
Fix Extra Space Bellow Sidebar Titles

### ISSUE THREAD

**Issue by RebeccaDeField** [HDDigitizerMusic/lmms-alt-theme#10]
I'm having trouble with the spacing on the sidebar. I feel like it should be pretty simple but I haven't been able to get it to work. If someone could give it a shot that would be much appriciated.

![space](https://cloud.githubusercontent.com/assets/7960169/12227495/5cf64e32-b7e2-11e5-9eec-9c7d5507acf5.png)

**Comment by RebeccaDeField** [comment]
This is on hold atm and a low priority.

**Comment by RebeccaDeField** [comment]
@Umcaruje I used the sizes for the sidebar icons that you had used in your flat theme. It seems that these icons are too small and therefore adding the extra space below the title. Is this a problem that you ran into in your theme as well?

Thank you for your time in advance.

**Comment by RebeccaDeField** [comment]
@Umcaruje Just wanted to follow up on my previous questions. Thank you :+1:

**Comment by Umcaruje** [comment]
Ah, sorry, I forgot to reply. The way I handled this is that I actually designed the icons in 16x16, but rendered them at double the scale, that is 32x32. This assures the icons will look crisp when downscaled, but also would enlarge nicely. You can achieve this by doubling the DPI in inkscape:
![screenshot from 2016-05-15 20 20 53](https://cloud.githubusercontent.com/assets/6282045/15275974/9e4a6048-1ada-11e6-849a-d6b76dbba483.png)

Hope this answers your question :+1: If you have any more, just ask, and if I forget to answer in a day or to free feel to poke me :3

**Comment by RebeccaDeField** [comment]
@Umcaruje Right, great idea! I had my DPI automatically set to 300 since I was working on some print materials at the time. I had manually reset for the icons because of that, which explains why mine is too small. Thanks for the heads up!

**Comment by RebeccaDeField** [comment]
Fixed :)
