### ISSUE TITLE
Scroll Bar Issue

### ISSUE THREAD

**Issue by RebeccaDeField** [HDDigitizerMusic/lmms-alt-theme#11]
All of the scroll bars are acting/looking just like Digitizer and I want, except for some reason the scroll bars in the Automation Editor and Piano Roll are wider and slightly overlap. I'm not sure why this is happening.

![goodscrollbar](https://cloud.githubusercontent.com/assets/7960169/12227713/c8e22758-b7e5-11e5-9e94-443800a1b9ba.png)
What the scroll bar is supposed to look like.

![ec53e15b-cfb1-4841-b3f4-477f877b878e](https://cloud.githubusercontent.com/assets/7960169/12227711/c46350d0-b7e5-11e5-84bb-ccb5e23e2369.png)
This is the problem I'm having.

**Comment by Umcaruje** [comment]
Did you change the graphics for the scrollbar buttons and/or their margins in the CSS? That is probably the problem, since it looks ok in the default theme, no overlapping.

**Comment by RebeccaDeField** [comment]
Yes, I did change the graphics and margins. All of the scrollbars in the entire program look fine with these margins and graphics except for in the Automation Editor and Piano Roll. I'm sure it's an error made somewhere, but I have been unable to locate it so far. I am continuing to search for the error, but I thought a more expirenced coder might have better luck.

**Comment by Umcaruje** [comment]
> Yes, I did change the graphics and margins. All of the scrollbars in the entire program look fine with these margins and graphics except for in the Automation Editor and Piano Roll. I'm sure it's an error made somewhere, but I have been unable to locate it so far. I am continuing to search for the error, but I thought a more expirenced coder might have better luck.

Ah, sorry I didn't see it was Piano Roll and Automation editor only. It overlaps in the master branch too. 

I'll look into it.

**Comment by RebeccaDeField** [comment]
@Umcaruje No problem. I didn't realize this was an error with the default theme as well. Thank you for your help with this.
