### ISSUE TITLE
Change Gray BG For Instruments In Sidebar

### ISSUE THREAD

**Issue by RebeccaDeField** [HDDigitizerMusic/lmms-alt-theme#12]
Digitizer and I can't seem to find the where change the currently gray background for instruments in the sidebar. This may be another hard coded element.

![instruments](https://cloud.githubusercontent.com/assets/7960169/12228298/1b221106-b7ee-11e5-8c0f-a097fdceb3ef.png)

**Comment by zonkmachine** [comment]
Yes, It's an upstream issue: https://github.com/LMMS/lmms/issues/2329

**Comment by RebeccaDeField** [comment]
@zonkmachine Glad to see that it's already being worked on, thanks!
