### ISSUE TITLE
Change Spacing Hover On Right Click Dialog

### ISSUE THREAD

**Issue by RebeccaDeField** [HDDigitizerMusic/lmms-alt-theme#13]
Digitizer and I think it would be nice to change the way that the right click dialog box looks. Right now when you hover over an item, the hover color only extends to the end of the elements. I would like it to expand to the edges, but was having some trouble getting it to work. Some assistance would be much appriciated!

![1](https://cloud.githubusercontent.com/assets/7960169/12371049/56f2510a-bbdb-11e5-9fb8-87eb5ca6c84e.png)
How it looks

![2](https://cloud.githubusercontent.com/assets/7960169/12371052/7e761310-bbdb-11e5-8d22-06d4dfa5aa72.png)
How I want it to look

**Comment by Umcaruje** [comment]
Change line: https://github.com/LMMS/lmms/blob/master/data/themes/default/style.css#L79

To `margin: 3px 0px 3px 0px;`

That'll achieve the look you are looking for.

**Comment by RebeccaDeField** [comment]
Thanks!

**Comment by RebeccaDeField** [comment]
Thanks for the help. When I used the code you provided on the line that you specified, the elments became flush to the left.

**Comment by Umcaruje** [comment]
could you commit so I see your `style.css`?

**Comment by RebeccaDeField** [comment]
I'll be able to make a commit soon so that you can see the `style.css` file, but please note that I need to rebase my fork soon to pull in all of the recent changes made on the master branch.

There are still some things in progress and there will be some updates that are missing at the moment.

**Comment by RebeccaDeField** [comment]
@Umcaruje Just committed the `style.css` file. You should be able to see what I am currently working with.

**Comment by RebeccaDeField** [comment]
@Umcaruje just wanted to clarify few things:
1. This might be a good update for the default theme as well.
2. This is a low priority compared to other tasks, so no pressure.

**Comment by Umcaruje** [comment]
> @Umcaruje just wanted to clarify few things:

Sure, but this really can be solved by adding some padding, I just haven't had the time to look at it. I'll issue a PR to add this to the default theme when I get around to it.

**Comment by Umcaruje** [comment]
@RebeccaDeField https://github.com/LMMS/lmms/pull/2567 here you go. It was just a matter of adjusting the padding of the `QMenu::item`

**Comment by RebeccaDeField** [comment]
Again, thank you! :+1: 

I have noticed that you have been very active lately, completing many tasks that other people need help with. It is very appreciated.

**Comment by Umcaruje** [comment]
> I have noticed that you have been very active lately, completing many tasks that other people need help with. It is very appreciated.

Glad I could help :smiley:
