### ISSUE TITLE
Remove Hard Coding From Knobs

### ISSUE THREAD

**Issue by RebeccaDeField** [HDDigitizerMusic/lmms-alt-theme#14]
So the knobs in the program are hard coded to look the way they do. I don't have much of a problem with how they currently look, but I would need the hard coding to be removed in order to make them look like my intial concept.

If this is not an easy task, I can just come up with a different idea for how the knobs will look in this theme.

This might be related to this issue #3

**Comment by Umcaruje** [comment]
Can you further explain how you want to change the look of the knobs please?

**Comment by RebeccaDeField** [comment]
You can see my initial idea for the knobs here.
![knobs](https://cloud.githubusercontent.com/assets/7960169/12970546/ee6ce09a-d044-11e5-82a5-ad23eecb18ea.png)

Now that I am more familiar with the program, I am planning on doing something a little more simplified. You will notice that the background of this knob is black all around instead of the darker shade of green that is currently in place.

I try to keep the elements and style as similar to my concept art for the theme as possible, but I am open to changes for elements that aren't worth the effort if it's too difficult.

**Comment by RebeccaDeField** [comment]
@Umcaruje I've been thinking about this and I am wondering if removing the hard coding will help with this #3 ?

If so, I might as well change the look of the knobs once done. If not, I will just come up with something different (it won't take much work on my end).

**Comment by RebeccaDeField** [comment]
@Umcaruje I did a ton of research on smaller yet stylized knobs and came to a new idea that I feel enhances the design. You can see my new concept below.

![knobidea](https://cloud.githubusercontent.com/assets/7960169/13481627/1c82e0a8-e09c-11e5-8868-908c046a9588.png)

What I ended up with is more flat and minimalistic. After comparing this design to what is currently in place, I realized that we don't need to remove any hard coding. I think we can close this issue now. :)

**Comment by Umcaruje** [comment]
> I think we can close this issue now. :)

:+1:
