### ISSUE TITLE
Update The Icons

### ISSUE THREAD

**Issue by RebeccaDeField** [HDDigitizerMusic/lmms-alt-theme#16]
Please see the discussion and updates bellow. Somehow I lost the original description for this issue :P

**Comment by Umcaruje** [comment]
I think he was talking about the controller icon (midi icon)

**Comment by RebeccaDeField** [comment]
@Umcaruje I see, thanks. :)

**Comment by DeRobyJ** [comment]
Tried something, but I'm the worst at drawing :(

![step_btn_add](https://cloud.githubusercontent.com/assets/6437521/13221796/6b957ad2-d97d-11e5-8596-badcdbcba87d.png) < [add] click the invisible icon
![step_btn_remove](https://cloud.githubusercontent.com/assets/6437521/13221797/6b9a4c60-d97d-11e5-8861-83a183be112c.png) < [remove]
![step_btn_duplicate](https://cloud.githubusercontent.com/assets/6437521/13221798/6ba13296-d97d-11e5-84be-6f76d0e66fab.png) < [dupl...whatever]
This one for duplicate is a bad idea... Just wanted to share anyway

What about the first two?

Anyway how do I quickly test the theme? Will replacing data/themes/default work?

**Comment by Umcaruje** [comment]
@DeRobyJ The icons are invisible, since they are white...

**Comment by DeRobyJ** [comment]
Well you could have downloaded them :v 

here they are onto black
![icons](https://cloud.githubusercontent.com/assets/6437521/13222223/50d377ba-d97f-11e5-8688-1ab5797368b8.png)

**Comment by RebeccaDeField** [comment]
Great ideas! I updated the icons based on your feedback and concepts. Does this make more sense?

![stepicons](https://cloud.githubusercontent.com/assets/7960169/13244048/211cb764-d9b8-11e5-9649-53519fbe0820.png)

**Comment by DeRobyJ** [comment]
It does!
But don't you think the plus and the minus should go to the block actually created/deleted, the one on the right?

Like them :)

**Comment by RebeccaDeField** [comment]
Like so?
![stepicons](https://cloud.githubusercontent.com/assets/7960169/13264358/9de1fca4-da22-11e5-90ee-b865c0083a34.png)

**Comment by DeRobyJ** [comment]
Yep :v:

**Comment by RebeccaDeField** [comment]
@IvanMaldonado I have made some tweaks to the gear icon. Does this look more gear, less flower?
![gear](https://cloud.githubusercontent.com/assets/7960169/13342289/f53457f8-dbf4-11e5-81c1-1d412d036384.png)

Can you also give me some examples of what you would like the controller icon to look like? I based it off of the default icon, but I am very open to new ideas.

**Comment by IvanMaldonado** [comment]
Sorry, I was on a trip.

@RebeccaDeField Looks much more like a gear :+1: 

I have to say I made a terrible mistake with the controller icon, I thought of it as a midi controller.
I don't understand how the original icon resembles a control though, but this is something out of my concern.

**Comment by RebeccaDeField** [comment]
No problem! I hope you enjoyed your trip :)

> Looks much more like a gear

Good to hear. :D

Also no problem on the controller icon, there are many icons and I can see how it can get confusing.

I believe that it is supposed to look like the knob moving from one side to another. Here is one idea that I have been thinking about.

![controller](https://cloud.githubusercontent.com/assets/7960169/13386970/04e84578-de67-11e5-952d-6c033fcc33b9.png)

Any other ideas/thoughts? @Umcaruje @tresf @DeRobyJ

**Comment by DeRobyJ** [comment]
Nice knob, but I believe LMMS has two different knobs of different sizes, doesn't it?

If I get any new idea, I'll open an issue :+1:

**Comment by Umcaruje** [comment]
> Any other ideas/thoughts? @Umcaruje @tresf @DeRobyJ

Well, its ok as an icon, but I don't know how its gonna look compared to the other icons, because all of them are full-on white.

**Comment by RebeccaDeField** [comment]
@DeRobyJ For the knobs, I already have a different design in mind (will post in another thread here.) This is an earlier idea for the controller icon that I thought _might_ work.

@Umcaruje Those were my thoughts exactly.

I'm not a producer so my question is: what comes to mind when you think of the controller and how can we use that metaphor to create an icon that makes sense to everyone?

**Comment by tresf** [comment]
> I'm not a producer so my question is: what comes to mind when you think of the controller and how can we use that metaphor to create an icon that makes sense to everyone?

A robot. :smiling_imp:

**Comment by RebeccaDeField** [comment]
> I'm not a producer so my question is: what comes to mind when you think of the controller and how can we use that metaphor to create an icon that makes sense to everyone?

@DeRobyJ @budislav @LocoMatt @michaelgregorius @Umcaruje @IvanMaldonado @musikBear

Just want to check and see if anyone else has an opinion about this.

**Comment by tresf** [comment]
My feedback has already been posted. :+1:

**Comment by RebeccaDeField** [comment]
@tresf Whoops, didn't mean to mention you there again, sorry :P

**Comment by budislav** [comment]
![knob](https://cloud.githubusercontent.com/assets/3619927/13547140/e32e956e-e2c5-11e5-9093-880a3a07c1d4.png)

**Comment by michaelgregorius** [comment]
In lmms/#2528 it was [decided](https://github.com/LMMS/lmms/issues/2528#issuecomment-187602545) to use an ADSR icon for the modulation tab. So for consistency it might make sense to use that icon here as well.

**Comment by tresf** [comment]
@michaelgregorius I think that was more visually around the envelope portion of things, not the LFO, etc.

**Comment by michaelgregorius** [comment]
@tresf Then the ADSR icon won't be a good fit for the plugins either because the LFO is on the same tab as the ADSR.

**Comment by tresf** [comment]
> @tresf Then the ADSR icon won't be a good fit for the plugins either because the LFO is on the same tab as the ADSR.

Nor will we have the HPF/LPF, et. al.  That doesn't make it bad at all IMO.  We've lived with the obsure "ENV/LFO" for years and it suffers translation problems.  To say ADSR "won't be good" I think is asking a bit much of a UI.

**Comment by RebeccaDeField** [comment]
I did a bit of research into other LFO Controller icons and it seems to me that a sine wave might be a good solution.

Here is an example: 
![sine](https://cloud.githubusercontent.com/assets/7960169/13694532/10d41aea-e70b-11e5-9ea0-a43a8ed766f8.png)

We could also always go with the knob as @budislav is saying. I'm not quite sure what @tresf has in mind with the robot, but [this](https://www.google.com/search?q=robot+icon&safe=active&source=lnms&tbm=isch&sa=X&ved=0ahUKEwjuy6K5j7_LAhUX_mMKHUPsC7AQ_AUIBygB&biw=1600&bih=745) is what comes up when I do a search.

**Comment by RebeccaDeField** [comment]
I haven't received any feedback on my previous idea yet, so I'm just going to go with a simple knob icon for now as Budislav suggested until/unless we can decide on something more specific. :)

@tresf @budislav @Umcaruje

**Comment by claell** [comment]
@RebeccaDeField I am not experienced at all with this, but I also agree that a wave might be better than a simple knob. You said that this icon is also used by other programs, so it looks good to me.

But as @michaelgregorius said it might be good to try to use a consistent icon. It seems that in #2528 a different icon is used for ENV/LFO, although I don't know, whether that is the same as a controller.

**Comment by RebeccaDeField** [comment]
@claell Thanks for the feedback! It is very helpful for me on when it comes to the aspects of producing that I know less about.

@tresf @budislav @michaelgregorius 
Would love to know if the wave makes sense to you as well?

**Comment by tresf** [comment]
> Would love to know if the wave makes sense to you as well?

I'm sorry if I wasn't clear.

In my opinion a sine wave is a bad representation of a controller rack or controller icon in general.  Per @budislav's feedback the fade-knob illustrate is more accurate to what the controller does.  The sine wave is used throughout the software to represent noise and sound generation, I'd rather it not used for a controller rack too.

Had I were deciding, I still thing a robot-themed icon would get the point across, FWIW. 

![image](https://cloud.githubusercontent.com/assets/6345473/14087266/03d9ab6c-f4f7-11e5-8dcd-1d3ffb93393a.png)

**Comment by RebeccaDeField** [comment]
@tresf Makes more sense now, thanks for the example. The robot icon actually seems to make the most sense so far. I can go ahead with this idea as long as I can get some confirmation from a couple of other people in the LMMS team that it works for them. :)

@michaelgregorius @claell

**Comment by claell** [comment]
@tresf So other programs don't use a wave icon for this? I don't really know, what a controller does, but a robot looks too geeky to me.

**Comment by tresf** [comment]
> I don't really know, what a controller does

Perhaps you should before weighing in on this topic.

**Comment by claell** [comment]
https://lmms.io/wiki/index.php?title=Controller_Rack I read this now. Still I think a robot icon looks a bit too geeky and also fits more an automation option than a controller (at least how I understand a controller).

I understand the argumentation of @tresf that a wave is mostly used for a different purpose in the program. So it might be confusing. How do other programs handle this? Do they use this icon for both or do they have a different solution?

**Comment by tresf** [comment]
>  How do other programs handle this? Do they use this icon for both or do they have a different solution?

According to @RebeccaDeField's research, https://github.com/HDDigitizerMusic/lmms-alt-theme/issues/16#issuecomment-195207643

> I think a robot icon looks a bit too geeky

You already said that.  The goal with constructive criticism is to be constructive, e.g. `construct`.  If you can't offer something to move forward, you should reconsider offering your opinion, or at least leave your opinion as a one-time read.  i.e. We heard you and no one disagreed with you, so your opinion is already being weighed.

There a several problems with using a glyph to represent an action, but there are equally great risks with making a creative decision a democracy.

Some rather confusing glyph examples... 
- A floppy disk is a bit geeky (albeit legacy) as a `File, Save` icon, yet interfaces use it all over the place.
- A paper airplane icon could be suggestive of foul play, or a vessel which never reaches its desired destination, but mobile mail apps insist on using this as the icon for "send"

In this case, @RebeccaDeField is the final decision, so please direct your comments to her.  I think the fading knob (https://github.com/HDDigitizerMusic/lmms-alt-theme/issues/16#issuecomment-190058577) was also well received, given @Umcaruje's contrast concerns...

**Comment by claell** [comment]
@tresf I meant whether they use the same icon for controller and 

> to represent noise and sound generation

or use a different approach.

I wrote that I still think so, because my previous opinion was not based on knowing what a Controller does.

This seems to be the current icon:

![controller_rack_button_1 0 0](https://cloud.githubusercontent.com/assets/6171135/14109451/62cc27be-f5c2-11e5-9b34-77e148cde9cc.png)

So probably a knob is a good decision.

**Comment by tresf** [comment]
> So probably a knob is a good decision

Perhaps something that illustrates movement on the knob? (crude mock-up warning!)

![image](https://cloud.githubusercontent.com/assets/6345473/14120564/4ba80ad6-f5c1-11e5-8b5d-486bd2cab100.png)

**Comment by claell** [comment]
Yes that is a good idea. I could also think of a sine wave on the knob to illustrate that the knob is controlled by the wave, but I don't know, whether the wave is big enough to be visible then and whether it makes sense or is rather irritating to the user.

**Comment by RebeccaDeField** [comment]
I mocked up a ton of ideas and here are the ones that I liked the best...
![controller](https://cloud.githubusercontent.com/assets/7960169/14165366/110c955c-f6bd-11e5-9013-c64a48ad39be.png)

I'm leaning towards the second option. The two tone knob (icon 3-4) matches the rest of my icon-set because I have used some shaded flat elements in other icons, unlike the gradient that was in my previous knob icon.

Looking forward to your feedback.

**Comment by DeRobyJ** [comment]
Imho, having arrows in a window full of knobs will be confusing...
I'd probably stick with the third, while the first is maybe too basic.

Lol at the sixth xD

**Comment by Umcaruje** [comment]
I like the 2nd and the 4th the best, but leaning towards the 2nd because of the contrast concerns. The 4th pic with a slightly higher opacity would be a winner for me.

**Comment by DeRobyJ** [comment]
I agree that the 4th would be better than the second if the dark part were not so dark!

**Comment by RebeccaDeField** [comment]
@DeRobyJ @Umcaruje Updated per feedback:
![controller](https://cloud.githubusercontent.com/assets/7960169/14186383/fc20f6d0-f732-11e5-917e-e31f12a9cc0d.png)

**Comment by RebeccaDeField** [comment]
I think that the icon in the comment above is much clearer than my original design. I am going to use this for my theme.

Thank you for all of the ideas and feedback!
