### ISSUE TITLE
Increase the pixel width of the number digits

### ISSUE THREAD

**Issue by RebeccaDeField** [HDDigitizerMusic/lmms-alt-theme#17]
Try increasing to 2px and see how if looks.

**Comment by RebeccaDeField** [comment]
@midi-pascal I increased the width of the numbers as requested. Is this more readable to you?

![lcd_19green](https://cloud.githubusercontent.com/assets/7960169/13201244/195053f2-d81d-11e5-90d3-0e16a04d4493.png)

**Comment by midi-pascal** [comment]
Wow! This is perfect :100:

**Comment by Umcaruje** [comment]
:+1: from me too

**Comment by RebeccaDeField** [comment]
Glad to hear it!
