### ISSUE TITLE
Update the BBeditor

### ISSUE THREAD

**Issue by RebeccaDeField** [HDDigitizerMusic/lmms-alt-theme#18]
Try decreasing the border width.

**Comment by RebeccaDeField** [comment]
As per @IvanMaldonado and @Spekular. I created more contrast between the steps and decreased the border width. I'm still unsure about the width of the border, but I have not yet decided. Please take a look and let me what you think.
![bbeditor](https://cloud.githubusercontent.com/assets/7960169/13201365/e170bf0c-d822-11e5-88bb-463914a1a028.png)

**Comment by Spekular** [comment]
These borders look good to me! It's awesome how fast you respond tp
feedback :)

**Comment by RebeccaDeField** [comment]
Perfect.

Thank you, I try :) Sometimes I can't respond as fast, but it really just depends on how busy I am.

**Comment by IvanMaldonado** [comment]
The contrast is clear to me now, thanks!
Also, I think the new border width makes them look much better :+1:
