### ISSUE TITLE
Update Contrast

### ISSUE THREAD

**Issue by RebeccaDeField** [HDDigitizerMusic/lmms-alt-theme#19]
Make the greys lighter. Make sure that all knobs and very readable. Experiment with off-white text.

**Comment by RebeccaDeField** [comment]
I think that we have all agreed on decreasing the contrast for this theme.

I tweaked the colors and have come to what I think will be an improved palette based on everyone's feedback. Please take a look and let us know what you think :)

![backgrounds](https://cloud.githubusercontent.com/assets/7960169/13483646/2e0ccf1e-e0ab-11e5-802e-3c58fb01cac1.png)
I will be using the primary color for most of the objects and backgrounds on the theme. The dark and light colors are for highlights/definition and will be used more sparingly. The text is now off-white instead of #fff due to some requests.

@DeRobyJ @Tresf @budislav @LocoMatt @michaelgregorius @Umcaruje @IvanMaldonado @musikBear

**Comment by tresf** [comment]
I'm quite fond of the last one there... :)

**Comment by RebeccaDeField** [comment]
@tresf Glad to hear it :)

I just want to clarify that the image above is the entire palette for BGs. I will be using all three of the shades.

**Comment by tresf** [comment]
@RebeccaDeField yes that was very clear. :+1:

**Comment by budislav** [comment]
Last one is the best on my monitor.

**Comment by RebeccaDeField** [comment]
I have updated the palette according to the feedback I have received. I think this will be a good base for the lighter colors, but we might make some tweaks when it's in the program.

![backgrounds](https://cloud.githubusercontent.com/assets/7960169/13689826/aa855ba2-e6e0-11e5-9ca7-f025bf6ad9bc.png)

**Comment by RebeccaDeField** [comment]
Alright, so I have decreased the contrast quite a bit and I like how things are looking. I've attached a screenshot with the updated colors.

![theme](https://cloud.githubusercontent.com/assets/7960169/14239911/46ccb4de-f9f5-11e5-9f91-ce278df9a849.png)

P.S. If anyone would like the contrast decreased further, this is something that can be done if/when the theme is moved into the PR.

**Comment by Umcaruje** [comment]
I just have one problem: the song editor grid is too dark to me, and I find it hard to see the lines and distinguish between the lighter and darker shade, and I'd really like if that part of the theme gets lightened up a bit.

P.S. The title bar PR should get merged soon, so all that's left is that the CSS gets updated on your end, and you can proceed with the PR ;)

**Comment by RebeccaDeField** [comment]
@Umcaruje Great observation. The colors for the song editor will be updated along with the other css updates so that we can move this into the PR.

P.S. I was really impressed with all of the hard work that everyone put into getting that wrapped up so quickly. I am in the process of updating the CSS as we speak (or type)

 I'm very excited at how fast things are progressing :smile:

**Comment by RebeccaDeField** [comment]
@Umcaruje Please see my newly coded up Song-Editor. Almost done with all of the other previously hard-coded elements as well. I will post more screenshots on the main issue tracker when it's ready :)

![shot-2016-05-15_10-39-44](https://cloud.githubusercontent.com/assets/7960169/15275799/06eec3d8-1a8a-11e6-8528-e04ddda28308.jpg)

Please note: the pressed buttons in this screenshot are not finished. I also plan on increasing the contrast a bit between the light and dark sections in the song-editor.

**Comment by DeRobyJ** [comment]
It's gorgeous!

**Comment by Umcaruje** [comment]
@RebeccaDeField looks better, but I think an even brighter line would help, as well as some contrast between the sections, as you noted.

**Comment by RebeccaDeField** [comment]
@Umcaruje Just wanted to give you a heads up that I made the changes in your comment above. More screenshots will be in my pull request. :)

**Comment by Umcaruje** [comment]
:+1:
