### ISSUE TITLE
Change The Colors

### ISSUE THREAD

**Issue by RebeccaDeField** [HDDigitizerMusic/lmms-alt-theme#4]
Some of the colors need to be updated to match the Wiki tutorials on LMMS so no that we can avoid any confusion.

**Comment by tresf** [comment]
> Some of the colors need to be updated to match the Wiki tutorials on LMMS so no that we can avoid any confusion.

Can you please clarify this task?

**Comment by RebeccaDeField** [comment]
I already talked to @HDDigitizerMusic about it and he made the changes. It will be in the next comit.

**Comment by tresf** [comment]
@RebeccaDeField great, but it would be nice to understand the task so that we can understand how it fits into the project.

**Comment by RebeccaDeField** [comment]
@tresf Someone mentioned that we had the wrong color for the automation tracks and the notes in the piano roll. In some wiki articles the color is referenced in the tutorial, so to avoid confusion we switched the colors back.

It might even be useful for someone to list all colors that have any significance in the theme besides the piano roll and automation tracks (if any), to insure that everything lines up correctly. :)

**Comment by tresf** [comment]
> @tresf Someone mentioned that we had the wrong color for the automation tracks and the notes in the piano roll. In some wiki articles the color is referenced in the tutorial, so to avoid confusion we switched the colors back.

Thanks for explaining.  I'd ask you to tag @Umcaruje to make sure we aren't sacrificing design over documentation.  If a tutorial says "click the black knob", we can just as easily change it to "click the knob". :)

**Comment by RebeccaDeField** [comment]
@tresf I agree. :+1: 

We only switched the blue and the green within the Modern Theme color palette. I thought that if making a tweak to the colors was important to @musikBear and didn't affect my design, that it wouldn't hurt.

As for the other colors, what I meant was that we would only need to make a change if there was a significant meaning/reason behind it being there.

I'm tagging @Umcaruje here per your request :)

**Comment by Umcaruje** [comment]
The documentation is already quite outdated tbh, so you shouldn't really pay that much attention to it. I'd rather change the docs, then sacrifice a good color scheme because of them. 

Also the quality control on our docs is pretty low, so it really needs a complete rehaul, but that's for another issue.

**Comment by RebeccaDeField** [comment]
@Umcaruje Sounds good. Thanks for the info. :)
