### ISSUE TITLE
Research Ways To Change The Window Borders

### ISSUE THREAD

**Issue by RebeccaDeField** [HDDigitizerMusic/lmms-alt-theme#5]
LMMS is built using Qt and and it uses Qt's QMdiArea. Every window inside LMMS is a QMdiSubwindow, and they are not themeable using CSS. Their look is hard-coded in the Qt settings for your PC.

A solution someone mentioned would be to actually render frameless windows and then draw a custom titlebar on top of them.

It was also mentioned that @Wallacoloo has already modified the QMdiSubWindow to fix maximising issues so he might have a clearer idea what would it take to implement a custom titlebar.

**Comment by Umcaruje** [comment]
Yup, that's pretty much the only solution. I guess this issue could also be suitable for the main issue tracker, since you'll get a lot more replies there, and its more of a general LMMS issue than a specific theme issue.

**Comment by Wallacoloo** [comment]
Oops, I missed this message the first time around - sorry. I don't have a
clear idea on how custom window borders would be handled in Qt. I just work
on the principle of trial and error when it comes to anything Qt :/

**Comment by RebeccaDeField** [comment]
@Umcaruje I added it to the main issue tracker. Would it work best if I close this issue here now or...?

**Comment by Umcaruje** [comment]
Yeah, this can be closed, since this is a general issue, and not a specific theme one.
