### ISSUE TITLE
Change Stroke Color On FX Mixer

### ISSUE THREAD

**Issue by RebeccaDeField** [HDDigitizerMusic/lmms-alt-theme#9]
@HDDigitizerMusic and I believe that the stroke style and color may be another hard coded element. We would like to make changes to it, but will need the hard coding to be removed first.

![stroke](https://cloud.githubusercontent.com/assets/7960169/12226402/488cdc0c-b7d0-11e5-9124-6925ce017917.png)

**Comment by Umcaruje** [comment]
Please name the current CSS property that changes the mixer color.

**Comment by RebeccaDeField** [comment]
The color of the inside of the element is edited under `FXLine`.

**Comment by Umcaruje** [comment]
Ok, I'm on it.

**Comment by Umcaruje** [comment]
https://github.com/LMMS/lmms/pull/2547 Will allow you to change the stroke to the finest details ;)

**Comment by RebeccaDeField** [comment]
Perfect, thank you :)
